apiVersion: v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
        - name: argocd-repo-server
          envFrom:
            - configMapRef:
                name: proxy-config