apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
  namespace: argo-events
spec:
  github:
    user-project:
      repositories:
        - owner: walk1ng
          names:
            - demo-user-project
      webhook:
        endpoint: /user-project
        port: "12000"
        method: POST
        url:  https://openly-delicate-escargot.ngrok-free.app
      events:
        - "push"
      apiToken:
        key: token
        name: github-access
      webhookSecret:
        key: secret
        name: github-access
      insecure: true
      active: true
      contentType: json
